# -*- coding: utf-8 -*-
"""missing_datawig.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LaR3Uqfr-CftWQ7uc8gtlCXURW0GrUHC
"""

import pandas as pd
import numpy as np
import datawig
import os

np.random.seed(777)

def missing_values_table(df):
        mis_val = df.isnull().sum()
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        return mis_val_table_ren_columns

if __name__ == "__main__":
  food_waste_known =pd.read_csv(os.path.join('..','preprocess', 'add_missing_total_data_final_known.csv'))
  missing_values_table(food_waste_known)

  missing = ['west_cnt', 'west_amt', 'deliv_cnt', 'deliv_amt', 'af_cnt', 'af_amt', 'asia_cnt', 'asia_amt', 'food_cnt', 'food_amt', 'fast_cnt', 'fast_amt', 'des_cnt', 'des_amt']
  missing_df = food_waste_known[missing]

  for i in missing:
    imputer = datawig.SimpleImputer(
        input_columns = list(set(missing).difference(i)), 
        output_column = i, 
    )

    imputer.fit(train_df=missing_df[~missing_df[i].isnull()])
    df_null_only = missing_df[missing_df[i].isnull()]
    np_imputed = imputer.predict(df_null_only)
    df_imputed = pd.DataFrame(np_imputed)

    for j in df_imputed.index:
      food_waste_known.loc[j, i] = df_imputed[i+'_imputed'][j]

  # 변환 후 데이터 확인
  missing_values_table(food_waste_known)

  food_waste_known.to_csv(os.path.join('..','preprocess', 'total_data_final_known_end.csv'), index=False)